### ISSUE TITLE
Check conversion and extraction functions for statistical correctness

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epiparameter#240]
The conversion functions start with `convert_` and the extraction functions start with `extract_`.

**Comment by chartgerink** [comment]
Thanks for pinging me on this! 🙏 Makes me feel very useful with my stats background 😂 

This comment is a lot, so I do my best to structure it and make it as easy to find what is relevant. Here's the relevant info:

* The functions that are checkmarked I would consider correct as-is. 
* I enumerate all the points I have per distribution so they are easier to reference throughout our discussion (without having to paste the exact comment time and again).
* I will update the comment with PR items when relevant.

## `convert_*`

- [x] convert_summary_stats_to_params
- [x] convert_params_to_summary_stats
- [x] get_sd
- [x] chk_ss

### [Log-normal](https://en.wikipedia.org/wiki/Log-normal_distribution)

- [ ] convert_params_lnorm
- [ ] convert_summary_stats_lnorm

1. I think that you may have switched these conversions around. ⚠️ 

For example, the median of the lognormal distribution is $\exp(\mu)$. Currently the median of the normal distribution is calculated as $\exp(\mu_{lnorm})$ in the package.

2. We know that a normal distribution can have $\mu = -\infty$ through $+\infty$. Yet, if I run `convert_summary_stats_lnorm(mean = -1, sd = 1)` it gives an error. This is unexpected behavior - what do you think? 

3. Vice versa, `convert_params_lnorm(meanlog = -4, sdlog = 1)` runs without any errors, where I would expect an error because all values in the log-normal distribution are non-negative by definition.

### [Gamma](https://en.wikipedia.org/wiki/Gamma_distribution)

1. Is there an explicit reason there is no support for the Gamma function based on shape and rate ($\alpha, \beta$)? Currently there is support for shape and scale.

- [x] convert_params_gamma
- [ ] convert_summary_stats_gamma

2. I am getting an error on `convert_summary_stats_gamma` when $\mu\geq0$ but it can be negative. Am I missing something here? I would expect there to be no limitation on the mean. ❓ 

3. I would check/assert that the shape and scale parameters are non-negative [around here](https://github.com/epiverse-trace/epiparameter/blob/7c5a0fb9c732fbfe45177ef055f66e75063e460a/R/convert_params.R#L349). 
4. I would write `(x$mean)^2` and `/ abs(x$mean)` to prevent negative values as well around the same area as point 3 above.

### [Weibull](https://en.wikipedia.org/wiki/Weibull_distribution)

- [ ] convert_params_weibull

1. Alternatively compute median based on shape + scale parameters instead of [using qweibull](https://github.com/epiverse-trace/epiparameter/blob/7c5a0fb9c732fbfe45177ef055f66e75063e460a/R/convert_params.R#L389): `scale * (log(2))^(1/shape)` (helps reduce dependency on `stats::` too).
2. Mode is calculated correctly, but the `max()` wrapper is not functioning as needed. If $k\leq1$ mode is 0, but if $k=.5$ (shape) I get mode = 1 instead of 0. For $k=.99$ I get a `NaN` ($\Gamma=1$ [scale] for my calculations here).
3. `ex_kurtosis` is a handful! It uses the `skewness` so I would go ahead and [not repeat the computation here](https://github.com/epiverse-trace/epiparameter/blob/7c5a0fb9c732fbfe45177ef055f66e75063e460a/R/convert_params.R#L397) - it helps reduce the complexity of this calculation too.
4. The complexity of `ex_kurtosis` also led to some omitted parameters like $\sigma^3$ and the final $-3$. I think it should be this
```
((gamma(1 + 4 / shape) * scale^4 - 4 * skewness * mean *
    sd^3 -  6 * mean^2 * sd^2 - mean^4) / (sd^4)) - 3
```

- [ ] convert_summary_stats_weibull

5. I am unable to verify these at the moment. Do you have a source for the origin of these formula's?

### [Negative binomial](https://en.wikipedia.org/wiki/Negative_binomial_distribution)

- [ ] convert_params_nbinom

1. Skewness is calculated as `(1 + prob) / sqrt(prob * dispersion)` - could you source this? I have an alternative one so want to double check this.
 
- [x] convert_summary_stats_nbinom

### [Geometric](https://en.wikipedia.org/wiki/Geometric_distribution)

- [x] convert_params_geom
- [x] convert_summary_stats_geom

---

I will follow up with comments regarding `extract_` later

**Comment by joshwlambert** [comment]
Thanks for the detailed comments. 

> Is there an explicit reason there is no support for the Gamma function based on shape and rate? Currently there is support for shape and scale.

I will make this an issue and add this feature in a new PR.

> For `convert_summary_stats_weibull()` I am unable to verify these at the moment. Do you have a source for the origin of these formula's?

I don't remember the source, but will try and find it.

**Comment by chartgerink** [comment]
Thanks for your patience on me getting back to the `extract_` functions.

All in all - these look very good. I would only propose to have some documentation around https://github.com/epiverse-trace/epiparameter/blob/056d7663d026e60daff64cbe39ecf3091335b56c/R/extract_param.R#L338 until the end of the function. These are critical parts that right now need to be taken at face value. They have statistical basis, probably, but it's hard to verify the veracity of this for me, as I am not a daily practitioner of these kinds of formulae anymore.

My only suggestion for future improvement is to allow users to pass the estimation method down to the `.extract_param` function - sometimes these things end up mattering in edge cases. However, that is not super urgent and I'd rather do once a need arises from the people using the package.

**Comment by joshwlambert** [comment]
> Skewness is calculated as (1 + prob) / sqrt(prob * dispersion) - could you source this? I have an alternative one so want to double check this.

I'm not sure where I got the current formula from. I can see if differs from the [skewness formula on wikipedia](https://en.wikipedia.org/wiki/Negative_binomial_distribution). Is the wikipedia formula the same as what you have?

**Comment by chartgerink** [comment]
> I'm not sure where I got the current formula from. I can see if differs from the [skewness formula on wikipedia](https://en.wikipedia.org/wiki/Negative_binomial_distribution). Is the wikipedia formula the same as what you have?

Yup! 👍 Thanks 😊

**Comment by joshwlambert** [comment]
Changed to `skewness <- (2 - prob) / sqrt((1 - prob) * dispersion)` in d1259ea39832fffa3615fa8b94a5a58936bd78d4.

**Comment by joshwlambert** [comment]
Closing this issue after the merging of #242. If there are aspects of the conversion or extraction functions that we would like to further discuss we can reopen this issue or open up a new issue.
