### ISSUE TITLE
Make truncation adjusted distributions the default?

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/epiparameter#243]
Currently the default seems to be providing the distribution with `"right_truncated": false` (or perhaps just the first that appears in the database. For example:

```
onset_to_death_period_in <-
  epiparameter::epidist_db(disease = "covid",epi_dist = "onset to death",single_epidist = T)
  
print(onset_to_death_period_in$summary_stats)
```
Returns the distribution from Linton et al with mean 14.5, rather than the more accurate distribution that adjusts for right truncation with mean 20.2. One option would be to have user define this if they want truncation adjustment (e.g. for [case studies like this in EpiNow2](https://github.com/epiforecasts/EpiNow2/pull/545)), but given it is almost always preferable, probably better to just provide automatically?

**Comment by joshwlambert** [comment]
I agree that because in most cases the truncation adjusted entries will be preferable, when available, I have updated `epidist_db()` to select them when specifying `single_epidist = TRUE` in PR #323.

The order of preference when `single_epidist = TRUE` is now:
1) subset to the entries that are parameterised
2) subset to the entries that have truncation adjustment (_new addition_ in #323)
3) select entry with the largest sample size
