### ISSUE TITLE
Getting problems when trying to do a basic print of epidist.

### ISSUE THREAD

**Issue by jlessler** [epiverse-trace/epiparameter#301]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [ X] I have the most recent version of this package and R
 - [X ] I have found a bug
 - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

Please include a brief description of the problem with a code example:

Get a error when I try to print epidist_db
```r
library(epiparameter)

db <- epidist_db()

db
```

I get the following error:
ERROR while rich displaying an object: Error in vapply(x, function(y) y$citation$DOI, FUN.VALUE = character(1)): values must be length 1,
 but FUN(X[[1]]) result is length 0

This is my R version:
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

Sys.info:
Sys.info()
                              sysname                               release
                              "Linux"  "5.15.146.1-microsoft-standard-WSL2"
                              version                              nodename
"#1 SMP Thu Jan 11 04:09:03 UTC 2024"                        "JLesslerYoga"
                              machine                                 login
                             "x86_64"

---------

**Comment by jlessler** [comment]
The problem appears to come from that on some operating systems (and or R versions) calling `citation$DOI` returns NULL since the doi value is actually stored as lower case `citation$doi`. This comes up on line 579 of `epidist_db.R`.

**Comment by jfunction** [comment]
Interesting issue - I'm interested to know why `epiparameter:::multi_epidist[[1]]$citation$DOI` works for me on Windows but not others (seemingly those using Linux). As referenced it's called here https://github.com/epiverse-trace/epiparameter/blob/7f69ecf377850b59db5ea2a8845ed85f42e2b2ab/R/epidist_db.R#L579 and the underlying issue is in https://github.com/epiverse-trace/epiparameter/blob/7f69ecf377850b59db5ea2a8845ed85f42e2b2ab/R/epidist_utils.R#L399 which assigns the name `doi` rather than `DOI`. Not sure what the fix should be though.

**Comment by jfunction** [comment]
Thanks to the awesome sleuthing above I was able to get to the bottom of this without too much additional effort and just wanted to report back. 

The underlying issue was that the [patch](https://github.com/wch/r-source/commit/68275d65536a91b297f1408ad4e5c6c7bf3b5129) fixing the case insensitive values issue was made 2 years ago as part of R 4.2.0 but Ubuntu is still stuck on 4.1.2 [see here](https://packages.ubuntu.com/jammy/all/r-base/download). Note the NEWS says it's for version 4.2.0.

I also confirmed with `` utils:::`$.bibentry` `` which shows `` else lapply(unclass(x), `[[`, tolower(name)) `` in the newer version (which I have on my Windows machine) but not on the older version (which my Ubuntu machine installed). I double checked the version of `utils` was tied to the version of R with `installed.packages()["utils",c("Package", "Version")]`.
