### ISSUE TITLE
Include column for delay_distn in list_distributions()

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/epiparameter#46]
It would be useful to have a `delay_distn` column returned by `epiparameter::list_distributions()`, to allow users to see range of functions available.

Also, at present it seems like `epiparameter::list_distributions() = epiparameter::list_distributions("incubation")` – should the function with NULL argument return the full list of available distributions?

**Comment by joshwlambert** [comment]
On the second point, a `NULL` argument would default back to `incubation` due to the way `match.arg()` works. Instead I will change the default from `incubation` to `all` to have the full list of distribution returned by default.

Please clarify the first point. Currently, `list_distributions()` returns the type of delay distribution (e.g. serial interval) and the distribution that parameterises it (e.g. gamma). If there are multiple records for a given pathogen it will return multiple rows which may have different distributions, depending on what the papers reported.  What would the `delay_distn` contain?

**Comment by adamkucharski** [comment]
For 1st point, main branch version seems to return 5 columns: `c("pathogen_id","study_id","year","size","distribution")`, so no entry for the type of delay distribution – unless I've missed something?

**Comment by joshwlambert** [comment]
Updates have been made to `list_distributions()` and now it also returns a column for the type of delay distribution (`type_id`).
